// 曲名読みデータ — キー形式: "albumId::trackIndex"
const YOMI_MAP = {

  // === Everything (1992) ===
  "everything::0": "ろーどあいみすゆー",
  "everything::1": "みすたーしゃいにんぐむーん",
  "everything::2": "きみがいたなつ",
  "everything::3": "かぜ",
  "everything::4": "ためいきのにちようび",
  "everything::5": "ともだちのままで",
  "everything::6": "ちるどれんずわーるど",

  // === Kind of Love (1992) ===
  "kind-of-love::0": "にじのかなたへ",
  "kind-of-love::1": "おーるばいまいせるふ",
  "kind-of-love::2": "ぶるー",
  "kind-of-love::3": "だきしめたい",
  "kind-of-love::4": "ぐっばいまいぐるーみーでいず",
  "kind-of-love::5": "でぃすたんす",
  "kind-of-love::6": "くるまのなかでかくれてきすをしよう",
  "kind-of-love::7": "ししゅんきのなつ",
  "kind-of-love::8": "ほしになれたら",
  "kind-of-love::9": "てぃーんえいじどりーむ",
  "kind-of-love::10": "いつのひにかふたりで",

  // === Versus (1993) ===
  "versus::0": "あなざーまいんど",
  "versus::1": "めいんすとりーとにいこう",
  "versus::2": "あんどあいくろーすとぅゆー",
  "versus::3": "りぷれい",
  "versus::4": "まーまれーどきっす",
  "versus::5": "しんきろう",
  "versus::6": "とうぼうしゃ",
  "versus::7": "らぶ",
  "versus::8": "さよならはゆめのなかへ",
  "versus::9": "まいらいふ",

  // === Atomic Heart (1994) ===
  "atomic-heart::0": "ぷりんてぃんぐ",
  "atomic-heart::1": "だんすだんすだんす",
  "atomic-heart::2": "らぶこねくしょん",
  "atomic-heart::3": "いのせんとわーるど",
  "atomic-heart::4": "くらすめいと",
  "atomic-heart::5": "くろすろーど",
  "atomic-heart::6": "じぇらしー",
  "atomic-heart::7": "えいじあ",
  "atomic-heart::8": "れいん",
  "atomic-heart::9": "あめのちはれ",
  "atomic-heart::10": "らうんどあばうと",
  "atomic-heart::11": "おーばー",

  // === 深海 (1996) ===
  "shinkai::0": "だいぶ",
  "shinkai::1": "しーらかんす",
  "shinkai::2": "てがみ",
  "shinkai::3": "ありふれたらぶすとーりー",
  "shinkai::4": "みらー",
  "shinkai::5": "めいきんぐそんぐす",
  "shinkai::6": "なもなきうた",
  "shinkai::7": "そーれっつげっとぅるーす",
  "shinkai::8": "りんじにゅーす",
  "shinkai::9": "ましんがんをぶっぱなせ",
  "shinkai::10": "ゆりかごのあるおかから",
  "shinkai::11": "とりこ",
  "shinkai::12": "はな",
  "shinkai::13": "しんかい",

  // === bolero (1997) ===
  "bolero::0": "ぷろろーぐ",
  "bolero::1": "えぶりしんぐいっつゆー",
  "bolero::2": "たいむましーんにのって",
  "bolero::3": "ぶらんどぅにゅーまいらばー",
  "bolero::4": "えすてーまおぶえす",
  "bolero::5": "しーそーげーむ",
  "bolero::6": "かさのしたのきみにつぐ",
  "bolero::7": "あらいぶ",
  "bolero::8": "しあわせのかてごりー",
  "bolero::9": "えぶりばでぃごーず",
  "bolero::10": "ぼれろ",
  "bolero::11": "とぅもろうねばーのーず",

  // === Discovery (1999) ===
  "discovery::0": "でぃすかばりー",
  "discovery::1": "ひかりのさすほうへ",
  "discovery::2": "ぷりずむ",
  "discovery::3": "あんだーしゃつ",
  "discovery::4": "にしえひがしえ",
  "discovery::5": "しんぷる",
  "discovery::6": "あいるびー",
  "discovery::7": "にせんろくびゃくいち",
  "discovery::8": "ららら",
  "discovery::9": "おわりなきたび",
  "discovery::10": "いめーじ",

  // === Q (2000) ===
  "q::0": "せんたーおぶゆにばーす",
  "q::1": "そのむこうへいこう",
  "q::2": "のっとふぁうんど",
  "q::3": "すろーすたーたー",
  "q::4": "されんだー",
  "q::5": "つよがり",
  "q::6": "じゅうにがつのせんとらるぱーくぶるーす",
  "q::7": "ともとこーひーとうそといぶくろ",
  "q::8": "ろーどむーびー",
  "q::9": "えぶりしんぐいずめいどふろまどりーむ",
  "q::10": "くちぶえ",
  "q::11": "はれるいあ",
  "q::12": "やすらげるばしょ",

  // === It's a Wonderful World (2002) ===
  "its-a-wonderful-world::0": "おーばちゅあ",
  "its-a-wonderful-world::1": "そせい",
  "its-a-wonderful-world::2": "でぃあわんだふるわーるど",
  "its-a-wonderful-world::3": "わんつーすりー",
  "its-a-wonderful-world::4": "かわいたきす",
  "its-a-wonderful-world::5": "ゆーすふるでいず",
  "its-a-wonderful-world::6": "ふぁすなー",
  "its-a-wonderful-world::7": "ばーどけーじ",
  "its-a-wonderful-world::8": "らぶはじめました",
  "its-a-wonderful-world::9": "ゆーふぉー",
  "its-a-wonderful-world::10": "どろーいんぐ",
  "its-a-wonderful-world::11": "きみがすき",
  "its-a-wonderful-world::12": "いつでもほほえみを",
  "its-a-wonderful-world::13": "やさしいうた",
  "its-a-wonderful-world::14": "いっつあわんだふるわーるど",

  // === シフクノオト (2004) ===
  "shifukunooto::0": "いわせてみてぇもんだ",
  "shifukunooto::1": "ぱどる",
  "shifukunooto::2": "てのひら",
  "shifukunooto::3": "くるみ",
  "shifukunooto::4": "はなことば",
  "shifukunooto::5": "ぴんくきみょうなゆめ",
  "shifukunooto::6": "ちのくだ",
  "shifukunooto::7": "からかぜのかえりみち",
  "shifukunooto::8": "えにー",
  "shifukunooto::9": "てんちょうばす",
  "shifukunooto::10": "たがため",
  "shifukunooto::11": "ひーろー",

  // === I ♥ U (2005) ===
  "i-love-u::0": "わーるずえんど",
  "i-love-u::1": "もんすたー",
  "i-love-u::2": "みらい",
  "i-love-u::3": "ぼくらのおと",
  "i-love-u::4": "あんどあいらぶゆー",
  "i-love-u::5": "くつひも",
  "i-love-u::6": "きゃんでぃ",
  "i-love-u::7": "らんにんぐはい",
  "i-love-u::8": "さいん",
  "i-love-u::9": "どあ",
  "i-love-u::10": "とべ",
  "i-love-u::11": "へだたり",
  "i-love-u::12": "せんすい",

  // === 四次元 Four Dimensions (2005) ===
  "four-dimensions::0": "よーいどん",

  // === HOME (2007) ===
  "home::0": "さけびいのり",
  "home::1": "うぇいくみーあっぷ",
  "home::2": "いろどり",
  "home::3": "ほうきぼし",
  "home::4": "あなざーすとーりー",
  "home::5": "ぴあのまん",
  "home::6": "もっと",
  "home::7": "やわらかいかぜ",
  "home::8": "ふぇいく",
  "home::9": "ぽけっとかすたねっと",
  "home::10": "さんらいず",
  "home::11": "しるし",
  "home::12": "とおりあめ",
  "home::13": "あんまりおぼえてないや",

  // === B-SIDE (2007) ===
  "b-side::0": "きみのことがいわはなにもかんがえられない",
  "b-side::1": "まいこんふぃでんすそんぐ",
  "b-side::2": "あめのちはれりみっくすばーじょん",
  "b-side::3": "ふらじゃいる",
  "b-side::4": "またあえるかな",
  "b-side::5": "らぶいずぶらいんどねす",
  "b-side::6": "たびびと",
  "b-side::7": "でるも",
  "b-side::8": "ひとりごと",
  "b-side::9": "へぶんりーきす",
  "b-side::10": "にしえひがしえいーすとりみっくす",
  "b-side::11": "せんきゅうひゃくきゅうじゅうきゅうねんなつおきなわ",
  "b-side::12": "さよならにせんいちねん",
  "b-side::13": "あいむそーりー",
  "b-side::14": "もうそうまんげつ",
  "b-side::15": "こんなふうにひどくむしあついひ",
  "b-side::16": "ほころび",
  "b-side::17": "まいすいーとはーと",
  "b-side::18": "ひびき",
  "b-side::19": "くるみふぉーざふぃるむしあわせなしょくたく",
  "b-side::20": "にしえひがしえうぇすとりみっくす",

  // === GIFT シングル (2007) ===
  "gift-single::0": "おうだんほどうをわたるひとたち",

  // === HANABI シングル (2008) ===
  "hanabi-single::0": "ただだきあって",
  "hanabi-single::1": "なつがおわるなつのひのおまーじゅ",

  // === SUPERMARKET FANTASY (2008) ===
  "supermarket-fantasy::0": "しゅうまつのこんふぃでんすそんぐ",
  "supermarket-fantasy::1": "はなび",
  "supermarket-fantasy::2": "えそら",
  "supermarket-fantasy::3": "こえ",
  "supermarket-fantasy::4": "しょうねん",
  "supermarket-fantasy::5": "たびだちのうた",
  "supermarket-fantasy::6": "くちがすべって",
  "supermarket-fantasy::7": "すいじょうばす",
  "supermarket-fantasy::8": "とうきょう",
  "supermarket-fantasy::9": "ろっくんろーる",
  "supermarket-fantasy::10": "ひつじほえる",
  "supermarket-fantasy::11": "かぜとほしとめびうすのわ",
  "supermarket-fantasy::12": "ぎふと",
  "supermarket-fantasy::13": "はなのにおい",

  // === SENSE (2010) ===
  "sense::0": "あい",
  "sense::1": "ぎたい",
  "sense::2": "はうる",
  "sense::3": "あいむとーきんぐあばうとらびん",
  "sense::4": "さんびゃくろくじゅうごにち",
  "sense::5": "ろっくんろーるはいきている",
  "sense::6": "ろざりーた",
  "sense::7": "あお",
  "sense::8": "ふぁんふぁーれ",
  "sense::9": "はる",
  "sense::10": "ぷれりゅーど",
  "sense::11": "ふぉーえばー",

  // === [(an imitation) blood orange] (2012) ===
  "an-imitation-blood-orange::0": "ひぷのーしす",
  "an-imitation-blood-orange::1": "まーしゅまろうでい",
  "an-imitation-blood-orange::2": "えんどおぶざでい",
  "an-imitation-blood-orange::3": "じょうとうく",
  "an-imitation-blood-orange::4": "ぴーしーず",
  "an-imitation-blood-orange::5": "いみてーしょんのき",
  "an-imitation-blood-orange::6": "かぞえうた",
  "an-imitation-blood-orange::7": "いんまいたうん",
  "an-imitation-blood-orange::8": "かことみらいとこうしんするおとこ",
  "an-imitation-blood-orange::9": "はっぴーそんぐ",
  "an-imitation-blood-orange::10": "いのりなみだのきどう",

  // === REFLECTION {Naked} (2015) ===
  "reflection-naked::0": "ふぁんたじー",
  "reflection-naked::1": "ふぁいとくらぶ",
  "reflection-naked::2": "しゃよう",
  "reflection-naked::3": "めろでぃー",
  "reflection-naked::4": "くものいと",
  "reflection-naked::5": "あいきゃんめいくいっと",
  "reflection-naked::6": "ろーりんろーりんぐ",
  "reflection-naked::7": "はなたれる",
  "reflection-naked::8": "まちのふうけい",
  "reflection-naked::9": "うんめい",
  "reflection-naked::10": "あしおとびーすとろんぐ",
  "reflection-naked::11": "わすれえぬひと",
  "reflection-naked::12": "ゆーめいくみーはっぴー",
  "reflection-naked::13": "じゅえりー",
  "reflection-naked::14": "れむ",
  "reflection-naked::15": "わるつ",
  "reflection-naked::16": "しんかろん",
  "reflection-naked::17": "げんちょう",
  "reflection-naked::18": "りふれくしょん",
  "reflection-naked::19": "とおくへと",
  "reflection-naked::20": "あいわなびーぜあ",
  "reflection-naked::21": "すたーてぃんぐおーばー",
  "reflection-naked::22": "みかん",

  // === 重力と呼吸 (2018) ===
  "juryoku-to-kokyu::0": "ゆあそんぐ",
  "juryoku-to-kokyu::1": "うみにてこころははだかになりたがる",
  "juryoku-to-kokyu::2": "しんぐるす",
  "juryoku-to-kokyu::3": "へあかむずまいらぶ",
  "juryoku-to-kokyu::4": "はこにわ",
  "juryoku-to-kokyu::5": "あでぃくしょん",
  "juryoku-to-kokyu::6": "でいばいでいあいけんくるのものがたり",
  "juryoku-to-kokyu::7": "あきがくれたきっぷ",
  "juryoku-to-kokyu::8": "ひまわり",
  "juryoku-to-kokyu::9": "ひふこきゅう",

  // === SOUNDTRACKS (2020) ===
  "soundtracks::0": "だんしんぐしゅーず",
  "soundtracks::1": "ぶらんどぅにゅーぷらねっと",
  "soundtracks::2": "たーんおーばー",
  "soundtracks::3": "きみとかさねたものろーぐ",
  "soundtracks::4": "ろすたいむ",
  "soundtracks::5": "どきゅめんたりーふぃるむ",
  "soundtracks::6": "ばーすでい",
  "soundtracks::7": "あざーず",
  "soundtracks::8": "ざそんぐおぶぷれいず",
  "soundtracks::9": "めもりーず",

  // === Mr.Children 2015-2021 & NOW (2021) ===
  "best-2015-2021::0": "ひかりのあとりえ",
  "best-2015-2021::1": "えいえん",
  "best-2015-2021::2": "いきろ",

  // === miss you (2023) ===
  "miss-you::0": "あいみすゆー",
  "miss-you::1": "ふぃふてぃーずまっぷ",
  "miss-you::2": "あおいりんご",
  "miss-you::3": "あーゆーすりーぴんぐうぇるうぃずあうとみー",
  "miss-you::4": "ろすと",
  "miss-you::5": "あーとかみのみえざるて",
  "miss-you::6": "あめのひのぱれーど",
  "miss-you::7": "ぱーてぃーいずおーばー",
  "miss-you::8": "うぃーはぶのーたいむ",
  "miss-you::9": "けものみち",
  "miss-you::10": "たそがれとつみき",
  "miss-you::11": "でじゃびゅ",
  "miss-you::12": "おはよう",

  // === 記憶の旅人 シングル (2024) ===
  "kioku-no-tabibito::0": "きおくのたびびと",

  // === in the pocket シングル (2024) ===
  "in-the-pocket::0": "いんざぽけっと",

  // === 産声 (2026) ===
  "ubugoe::0": "きんぐすねーくのゆううつ",
  "ubugoe::1": "あげいん",
  "ubugoe::2": "さたでい",
  "ubugoe::3": "うすばかげろう",
  "ubugoe::4": "ぐらすとんべりー",
  "ubugoe::5": "きんだんのみ",
  "ubugoe::6": "へいねつ",
  "ubugoe::7": "くうやしょうにん",
  "ubugoe::8": "すとぅーぴっどひーろー",
  "ubugoe::9": "のーうぇあまん",
  "ubugoe::10": "うぶごえ",
  "ubugoe::11": "あんぶれら",
  "ubugoe::12": "かぞく",

};
